//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AI.broken {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="MTRANS_WEB", ConfigurationName="broken.wsPrcSATSOAPSoapPort")]
    public interface wsPrcSATSOAPSoapPort {
        
        // CODEGEN: Generating message contract since the wrapper name (wsPrcSATSOAP.Execute) of message ExecuteRequest does not match the default value (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="MTRANS_WEBaction/AWSPRCSATSOAP.Execute", ReplyAction="*")]
        AI.broken.ExecuteResponse Execute(AI.broken.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="MTRANS_WEBaction/AWSPRCSATSOAP.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<AI.broken.ExecuteResponse> ExecuteAsync(AI.broken.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsPrcSATSOAP.Execute", WrapperNamespace="MTRANS_WEB", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="MTRANS_WEB", Order=0)]
        public int Clicod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="MTRANS_WEB", Order=1)]
        public string Clipsw;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="MTRANS_WEB", Order=2)]
        public short Ediprocod;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="MTRANS_WEB", Order=3)]
        public string Datosentrada;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(int Clicod, string Clipsw, short Ediprocod, string Datosentrada) {
            this.Clicod = Clicod;
            this.Clipsw = Clipsw;
            this.Ediprocod = Ediprocod;
            this.Datosentrada = Datosentrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="wsPrcSATSOAP.ExecuteResponse", WrapperNamespace="MTRANS_WEB", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="MTRANS_WEB", Order=0)]
        public string Respuesta;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(string Respuesta) {
            this.Respuesta = Respuesta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsPrcSATSOAPSoapPortChannel : AI.broken.wsPrcSATSOAPSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsPrcSATSOAPSoapPortClient : System.ServiceModel.ClientBase<AI.broken.wsPrcSATSOAPSoapPort>, AI.broken.wsPrcSATSOAPSoapPort {
        
        public wsPrcSATSOAPSoapPortClient() {
        }
        
        public wsPrcSATSOAPSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsPrcSATSOAPSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPrcSATSOAPSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPrcSATSOAPSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AI.broken.ExecuteResponse AI.broken.wsPrcSATSOAPSoapPort.Execute(AI.broken.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public string Execute(int Clicod, string Clipsw, short Ediprocod, string Datosentrada) {
            AI.broken.ExecuteRequest inValue = new AI.broken.ExecuteRequest();
            inValue.Clicod = Clicod;
            inValue.Clipsw = Clipsw;
            inValue.Ediprocod = Ediprocod;
            inValue.Datosentrada = Datosentrada;
            AI.broken.ExecuteResponse retVal = ((AI.broken.wsPrcSATSOAPSoapPort)(this)).Execute(inValue);
            return retVal.Respuesta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AI.broken.ExecuteResponse> AI.broken.wsPrcSATSOAPSoapPort.ExecuteAsync(AI.broken.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<AI.broken.ExecuteResponse> ExecuteAsync(int Clicod, string Clipsw, short Ediprocod, string Datosentrada) {
            AI.broken.ExecuteRequest inValue = new AI.broken.ExecuteRequest();
            inValue.Clicod = Clicod;
            inValue.Clipsw = Clipsw;
            inValue.Ediprocod = Ediprocod;
            inValue.Datosentrada = Datosentrada;
            return ((AI.broken.wsPrcSATSOAPSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
